[tools]
tuist = "4.191.4"
swiftlint = "0.63.2"
swiftformat = "0.61.1"
pnpm = "10.33.2"
node = "24.15.0"
git-cliff = "2.13.1"
"npm:prettier" = "3.8.3"

[hooks]
postinstall = "mise run install"

[settings]
experimental = true
