# fly.toml app configuration file generated for noora-storybook on 2025-06-03T17:41:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'noora-storybook'
primary_region = 'fra'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'storybook.noora.tuist.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
  memory = "512MB"
