#!/bin/bash
# mise description="Lint the CLI package using SwiftLint and SwiftFormat"
#USAGE flag "-f --fix" help="Fix the fixable issues"

set -eo pipefail

if [ "$usage_fix" = "true" ]; then
  swiftformat cli
  swiftlint lint --fix --quiet --config cli/.swiftlint.yml cli/Sources
else
  swiftformat cli --lint
  swiftlint lint --quiet --config cli/.swiftlint.yml cli/Sources
fi

