#!/bin/bash
# mise description="Lint the CLI package using SwiftLint and SwiftFormat"
#USAGE flag "-f --fix" help="Fix the fixable issues"

set -eo pipefail

if [ "$usage_fix" = "true" ]; then
  swiftformat packages/cli
  swiftlint lint --fix --quiet --config packages/cli/.swiftlint.yml packages/cli/Sources
else
  swiftformat packages/cli --lint
  swiftlint lint --quiet --config packages/cli/.swiftlint.yml packages/cli/Sources
fi

