#!/bin/bash
# mise description="Lint the web package using mix format and prettier"
#USAGE flag "-f --fix" help="Fix the fixable issues"

set -eo pipefail

cd packages/web

if [ "$usage_fix" = "true" ]; then
  mix format
  pnpm prettier --write "js/**/*.js" "css/**/*.css"
else
  mix format --check-formatted
  pnpm prettier --check "js/**/*.js" "css/**/*.css"
fi

