#!/bin/bash
# mise description="Lint all packages"
#USAGE flag "-f --fix" help="Fix the fixable issues"

set -eo pipefail

echo "Linting CLI package..."
if [ "$usage_fix" = "true" ]; then
  mise run cli:lint --fix
  mise run web:lint --fix
else
  mise run cli:lint
  mise run web:lint
fi
