#!/bin/bash
# mise description="Lint all packages"
#USAGE flag "-f --fix" help="Fix the fixable issues"

set -eo pipefail

if [ "$usage_fix" = "true" ]; then
  mise run cli:lint --fix
else
  mise run cli:lint
fi
