#!/bin/bash
# mise description="Lint the CLI package using SwiftLint and SwiftFormat"
#USAGE flag "-f --fix" help="Fix the fixable issues"

set -eo pipefail

if [ "$usage_fix" = "true" ]; then
    swiftformat $MISE_PROJECT_ROOT/packages/cli
    swiftlint lint --fix --quiet --config $MISE_PROJECT_ROOT/.swiftlint.yml $MISE_PROJECT_ROOT/packages/cli/Sources
else
    swiftformat $MISE_PROJECT_ROOT/packages/cli --lint
    swiftlint lint --quiet --config $MISE_PROJECT_ROOT/.swiftlint.yml $MISE_PROJECT_ROOT/packages/cli/Sources
fi