#!/bin/bash
# mise description="Tests the CLI package using Swift Package Manager in Linux"
set -euo pipefail

podman run --rm \
    --volume "$MISE_PROJECT_ROOT:/package" \
    --workdir "/package/packages/cli" \
    swift:6.0.0 \
    /bin/bash -c \
    "swift test --build-path ./.build/linux"
