name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release"
        type: string

permissions:
  contents: write
  pull-requests: read
  statuses: write
  packages: write

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: "ubuntu-latest"
    if: "!startsWith(github.event.head_commit.message, '[Release]')"
    outputs:
      cli-changed: ${{ steps.changes.outputs.cli-changed }}
      web-changed: ${{ steps.changes.outputs.web-changed }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Detect package changes
        id: changes
        run: |
          # Get the list of changed files since the last release commit
          LAST_RELEASE=$(git log --oneline --grep="\[Release\]" -1 --format="%H" || echo "HEAD~10")

          # Check for CLI changes
          if git diff --name-only $LAST_RELEASE..HEAD | grep -E '^packages/cli/' > /dev/null; then
            echo "cli-changed=true" >> $GITHUB_OUTPUT
            echo "CLI package has changes"
          else
            echo "cli-changed=false" >> $GITHUB_OUTPUT
            echo "CLI package has no changes"
          fi

          # Check for Web changes
          if git diff --name-only $LAST_RELEASE..HEAD | grep -E '^packages/web/' > /dev/null; then
            echo "web-changed=true" >> $GITHUB_OUTPUT
            echo "Web package has changes"
          else
            echo "web-changed=false" >> $GITHUB_OUTPUT
            echo "Web package has no changes"
          fi

  release-cli:
    name: Release CLI
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    needs: detect-changes
    if: needs.detect-changes.outputs.cli-changed == 'true'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Check for CLI changes since last release
        id: check-changes
        run: |
          # Check if there are any commits affecting the CLI package since the last CLI release
          # CLI accepts both old unprefixed tags (e.g., "1.2.3") and new prefixed tags (e.g., "cli-1.2.3")
          LAST_CLI_TAG=$(git tag -l | grep -E '^(cli-[0-9]+\.[0-9]+\.[0-9]+|[0-9]+\.[0-9]+\.[0-9]+)$' | grep -v '^web-' | sort -V | tail -n 1)
          if [ -z "$LAST_CLI_TAG" ]; then
            echo "No previous CLI releases found, will release"
            echo "has-changes=true" >> $GITHUB_OUTPUT
          else
            if git diff --name-only ${LAST_CLI_TAG}..HEAD | grep -E '^packages/cli/' > /dev/null; then
              echo "CLI changes found since $LAST_CLI_TAG"
              echo "has-changes=true" >> $GITHUB_OUTPUT
            else
              echo "No CLI changes since $LAST_CLI_TAG"
              echo "has-changes=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Get next version
        id: next-version
        if: steps.check-changes.outputs.has-changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEXT_VERSION=$(git cliff --config packages/cli/cliff.toml --bumped-version)
          echo "NEXT_VERSION=$NEXT_VERSION" >> "$GITHUB_OUTPUT"
          echo "Next CLI version will be: $NEXT_VERSION"

      - name: Update CHANGELOG.md
        if: steps.check-changes.outputs.has-changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git cliff --config cli/cliff.toml --bump -o cli/CHANGELOG.md
      - name: Get release notes
        id: release-notes
        if: steps.check-changes.outputs.has-changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "RELEASE_NOTES<<EOF" >> "$GITHUB_OUTPUT"
          git cliff --config cli/cliff.toml --latest >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.check-changes.outputs.has-changes == 'true'
        with:
          commit_options: "--allow-empty"
          tagging_message: cli-${{ steps.next-version.outputs.NEXT_VERSION }}
          skip_dirty_check: true
          commit_message: "[Release] Noora CLI ${{ steps.next-version.outputs.NEXT_VERSION }}"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: steps.check-changes.outputs.has-changes == 'true'
        with:
          draft: false
          repository: tuist/Noora
          name: CLI ${{ steps.next-version.outputs.NEXT_VERSION }}
          tag_name: cli-${{ steps.next-version.outputs.NEXT_VERSION }}
          body: ${{ steps.release-notes.outputs.RELEASE_NOTES }}
          target_commitish: ${{ steps.auto-commit-action.outputs.commit_hash }}

  release-web:
    name: Release Web
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    needs: detect-changes
    if: needs.detect-changes.outputs.web-changed == 'true'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Install dependencies and build assets
        run: |
          cd packages/web
          pnpm install
          pnpm run build
      - name: Check for Web changes since last release
        id: check-changes
        run: |
          # Check if there are any commits affecting the Web package since the last Web release
          LAST_WEB_TAG=$(git tag -l "web-*" --sort=-version:refname | head -n 1)
          if [ -z "$LAST_WEB_TAG" ]; then
            echo "No previous Web releases found, will release"
            echo "has-changes=true" >> $GITHUB_OUTPUT
          else
            if git diff --name-only ${LAST_WEB_TAG}..HEAD | grep -E '^packages/web/' > /dev/null; then
              echo "Web changes found since $LAST_WEB_TAG"
              echo "has-changes=true" >> $GITHUB_OUTPUT
            else
              echo "No Web changes since $LAST_WEB_TAG"
              echo "has-changes=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Get next version
        id: next-version
        if: steps.check-changes.outputs.has-changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEXT_VERSION=$(git cliff --config packages/web/cliff.toml --bumped-version)
          echo "NEXT_VERSION=$NEXT_VERSION" >> "$GITHUB_OUTPUT"
          echo "Next Web version will be: $NEXT_VERSION"

      - name: Update version in mix.exs
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          sed -i 's/version: "[^"]*"/version: "${{ steps.next-version.outputs.NEXT_VERSION }}"/' packages/web/mix.exs

      - name: Update CHANGELOG.md
        if: steps.check-changes.outputs.has-changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git cliff --config packages/web/cliff.toml --bump -o packages/web/CHANGELOG.md

      - name: Get release notes
        id: release-notes
        if: steps.check-changes.outputs.has-changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "RELEASE_NOTES<<EOF" >> "$GITHUB_OUTPUT"
          git cliff --config packages/web/cliff.toml --latest >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.check-changes.outputs.has-changes == 'true'
        with:
          commit_options: "--allow-empty"
          tagging_message: web-${{ steps.next-version.outputs.NEXT_VERSION }}
          skip_dirty_check: true
          commit_message: "[Release] Noora Web ${{ steps.next-version.outputs.NEXT_VERSION }}"
      - name: Publish to Hex
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          cd packages/web
          mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: steps.check-changes.outputs.has-changes == 'true'
        with:
          draft: false
          repository: tuist/Noora
          name: Web ${{ steps.next-version.outputs.NEXT_VERSION }}
          tag_name: web-${{ steps.next-version.outputs.NEXT_VERSION }}
          body: ${{ steps.release-notes.outputs.RELEASE_NOTES }}
          target_commitish: ${{ steps.auto-commit-action.outputs.commit_hash }}
